name: MinecraftRestaurants
version: '${project.version}'
main: me.equaferrous.minecraftrestaurants.MinecraftRestaurants
api-version: 1.18
authors: [ EquaFerrous ]
description: Run a restaurant and serve customers.
commands:
